#ifndef GUARD_CONSTANTS_FLAGS_H
#define GUARD_CONSTANTS_FLAGS_H

#define FLAG_REPORT2 0x3A7
#define FLAG_REPORT3 0x3A8
#define FLAG_REPORT4 0x3A9
#define FLAG_REPORT5 0x3AA
#define FLAG_REPORT6 0x3AB

#endif // GUARD_CONSTANTS_FLAGS_H